### ISSUE TITLE
Windows 10 Version 1607

### ISSUE THREAD

**Issue by fdncred** [jamie-pate/flipflop-windows-wheel#5]
Windows seems to be ignoring the FlipFlopWheel flag now.  I'm not sure why but it doesn't work any longer. The only solution I've found so far is AutoHotKey. Any ideas?

**Comment by jamie-pate** [comment]
You definitely removed and re-added the device on the same usb port? It only notices that the registry key has changed during device connection.

**Comment by fdncred** [comment]
Yes. Removing and adding the mouse makes no difference.

**Comment by fdncred** [comment]
Installing KB3176929 and rebooting seems to have reverted things.  Maybe there was a bug that they fixed with the first 1607 Windows 10 Anniversary Update release.  Who knows. But for now, sorry for the false alarm. I'll reopen this if it reverts itself again.
